"""
Test script for the Underrated Locations Guide App
"""

import sys
import os

# Add src directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from guide_app import UnderratedGuideApp
import json

def test_config_loading():
    """Test configuration loading.

    The test simply verifies that the ``UnderratedGuideApp`` can be instantiated
    with the default configuration file without raising an exception.
    """
    # Instantiation should succeed; any exception will cause the test to fail.
    app = UnderratedGuideApp(config_file="config/config.json")
    assert isinstance(app, UnderratedGuideApp)
    return True

def test_location_detection():
    """Test location type detection.

    The ``detect_location_type`` method should map OSM tag dictionaries to the
    expected category strings as defined by ``_infer_category``.
    """
    app = UnderratedGuideApp(config_file="config/config.json")

    test_cases = [
        ({"natural": "water", "name": "River"}, "Nature"),
        ({"tourism": "viewpoint", "name": "Lookout"}, "Viewpoint"),
        ({"leisure": "park", "name": "City Park"}, "Park"),
        ({"name": "Unknown Location"}, "Other"),
    ]

    for tags, expected in test_cases:
        location_type = app.detect_location_type(tags)
        assert location_type == expected, f"Expected {expected}, got {location_type}"
    return True

def test_fallback_analysis():
    """Test fallback analysis generation.

    The ``create_fallback_analysis`` method should return a dictionary with the
    expected keys and values based on the provided tags and explicit category.
    """
    app = UnderratedGuideApp(config_file="config/config.json")

    test_tags = {"name": "Test River", "natural": "water"}
    analysis = app.create_fallback_analysis(test_tags, "water")

    # Verify the structure of the analysis result
    assert isinstance(analysis, dict)
    assert analysis["name"] == "Test River"
    assert analysis["category"] == "water"
    # ``description`` should be a non‑empty string generated by ``_build_description``
    assert isinstance(analysis["description"], str) and analysis["description"]
    # ``tags`` should be a JSON‑safe representation of the original tags
    assert analysis["tags"] == {"name": "Test River", "natural": "water"}
    return True

def main():
    """Run all tests"""
    print("🧪 Running Guide App Tests")
    print("=" * 40)

    tests = [
        test_config_loading,
        test_location_detection,
        test_fallback_analysis
    ]

    passed = 0
    total = len(tests)

    for test in tests:
        if test():
            passed += 1

    print(f"\n📊 Test Results: {passed}/{total} tests passed")

    if passed == total:
        print("✅ All tests passed! The app is ready to use.")
    else:
        print("❌ Some tests failed. Please check the implementation.")

    return passed == total

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)